<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>2.0.0.0</Version>
        <Use_DalamudPackager>false</Use_DalamudPackager>
        <Title>NoireLib - A library for Dalamud Plugins</Title>
        <Authors>Aspher0</Authors>
        <Description>A flexible library for creating Dalamud Plugins.</Description>
        <Copyright>© 2026 Aspher0</Copyright>
        <RepositoryUrl>https://github.com/Aspher0/NoireLib</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>NoireLib;Dalamud;Plugin;Dalamud Plugin;Aspher0;Plugins;Library;Plugin Library</PackageTags>
        <NeutralLanguage>en</NeutralLanguage>
        <PackageId>NoireLib</PackageId>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>Nuget_README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PublishDocumentationFile>true</PublishDocumentationFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release;PublicRelease</Configurations>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
      <DebugType>none</DebugType>

      <Optimize>true</Optimize>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
      <DebugType>none</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='PublicRelease'">
      <NoireExcludeAutomation>true</NoireExcludeAutomation>
      <Optimize>true</Optimize>
      <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\LICENSE">
          <Pack>True</Pack>
          <PackagePath>\</PackagePath>
        </None>
        
        <None Include="..\Nuget_README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
        
        <None Include="README.md" />
        <None Include="Automation\Actions\README.md" />
        <None Include="database\README.md" />
        <None Include="ipc\README.md" />
        <None Include="Configuration\README.md" />
        <None Include="Helpers\AddonHelper\README.md" />
        <None Include="Helpers\ShareCode\README.md" />
        <None Include="Helpers\EncryptionHelper\README.md" />
        <None Include="Helpers\GameData\README.md" />
        <None Include="Helpers\FuzzyMatcher\README.md" />
        <None Include="Helpers\Geometry\README.md" />
        <None Include="Modules\ChangelogManager\README.md" />
        <None Include="Modules\EventBus\README.md" />
        <None Include="Modules\ObservedStore\README.md" />
        <None Include="Modules\GameWatcher\README.md" />
        <None Include="modules\filewatcher\README.md" />
        <None Include="modules\historylogger\README.md" />
        <None Include="modules\networker\README.md" />
        <None Include="modules\commandrouter\README.md" />
        <None Include="modules\tweakmanager\README.md" />
        <None Include="modules\hotkeymanager\README.md" />
        <None Include="modules\localizer\README.md" />
        <None Include="Modules\TaskQueue\README.md" />
        <None Include="Modules\UpdateTracker\README.md" />
        <None Include="UI\README.md" />
        <None Include="Draw3D\README.md" />
        <None Include="Draw3D\Interaction\README.md" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Draw3D\Shaders\*.hlsl*" />
        <EmbeddedResource Include="Automation\Navigation\Data\navdata.json" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="TerraFX.Interop.Windows">
            <HintPath>$(DalamudLibPath)TerraFX.Interop.Windows.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="Dalamud.Bindings.ImGuizmo">
            <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGuizmo.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="HexaGen.Runtime">
            <HintPath>$(DalamudLibPath)HexaGen.Runtime.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NoireLib.SourceGenerators\NoireLib.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\NoireLib.SourceGenerators\bin\$(Configuration)\netstandard2.0\NoireLib.SourceGenerators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
        <PackageReference Include="Castle.Core" Version="5.2.1" />
        <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="SharpGLTF.Core" Version="1.0.6" />
        <PackageReference Include="System.Data.SQLite" Version="2.0.3" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
    </ItemGroup>

    <ItemGroup Condition="'$(NoireExcludeAutomation)'=='true'">
        <Compile Remove="Automation\**" />
        <None Remove="Automation\**" />
        <EmbeddedResource Remove="Automation\**" />

        <Compile Remove="Modules\GameWatcher\Actions Integration\**" />
        <None Remove="Modules\GameWatcher\Actions Integration\**" />
    </ItemGroup>
</Project>
